### ISSUE TITLE
be able to run junit tests and then compile things

### ISSUE THREAD

**Issue by fommil** [fommil/sbt-big-project#30]
i.e. workaround https://github.com/sbt/sbt/issues/2496

**Comment by fommil** [comment]
this might work for the scripted test here, but it's still failing for me at work.

**Comment by fommil** [comment]
could be the difference between openjdk and oraclejdk (work is `build 1.7.0_80-b15`)

**Comment by fommil** [comment]
appveyor uses u79, but I can't see why this would be any different http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html

**Comment by fommil** [comment]
might also be a thread visibility thing, we always knew changing a `private final` field could cause problems.

**Comment by fommil** [comment]
YourKit shows that the "pending finalization" instance has an incoming reference from a `URLClassPath$JarLoader` which is in a `HashMap`... so perhaps `closeLoaders()` isn't doing a good enough job!

**Comment by fommil** [comment]
heap analysis suggests that there is one `URLClassLoader` that is not being cleaned up.

**Comment by fommil** [comment]
adding to `loadedTestFrameworks` didn't help. I don't know where the extra classloader is being loaded.

The other thing to bare in mind is that I'm using sbt 0.13.9 at work, so maybe something in 0.13.11 classloading subtly changed?

**Comment by fommil** [comment]
another hint: it's referenced eventually by the https://docs.oracle.com/javase/7/docs/api/java/util/ResourceBundle.html

```
"Name","Retained Size","Shallow Size","Level"
"[Pending Finalization] java.util.jar.JarFile name = ""D:\my\thing_test_2.11-0.1-SNAPSHOT-tests.jar""","64","64", "1"
"jar of [Weak/Soft Reachable] sun.misc.URLClassPath$JarLoader","48","48", "2"
"[0] of [Weak/Soft Reachable] java.lang.Object[823]","3312","3312", "3"
"elementData of [Weak/Soft Reachable] java.util.ArrayList size = 558","24","24", "4"
"loaders of [Weak/Soft Reachable] sun.misc.URLClassPath","40","40", "5"
"ucp of [Weak/Soft Reachable] sbt.classpath.ClasspathUtilities$$anon$1","112","112", "6"
"referent of java.util.ResourceBundle$LoaderReference","32","32", "7"
"loaderRef of java.util.ResourceBundle$CacheKey","56","56", "8"
"cacheKey of java.util.ResourceBundle$1","40","40", "9"
"NONEXISTENT_BUNDLE of java.util.ResourceBundle [Class]","624","624", "10"
```

**Comment by fommil** [comment]
could be one of the other test runners. I disabled everything except JUnit and the file lock didn't happen (also didn't run any tests, but that's a different problem)

**Comment by fommil** [comment]
confirmed, it's the ScalaTest runner. Bloody hell, when will the madness end?

**Comment by fommil** [comment]
we should also test for being able to run the tests again, because I was getting errors during compile when just using JUnit that looked like the `scalac` classloader was in a bad state :sob:

**Comment by fommil** [comment]
`master` now has a reproduction of the junit exception and more file deletion trouble

**Comment by fommil** [comment]
```
[info] [error] Execution of test EmptyTest failed: java.lang.ClassNotFoundException: EmptyTest
[info] [error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[info] [error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[info] [error]     at java.security.AccessController.doPrivileged(Native Method)
[info] [error]     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[info] [error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[info] [error]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[info] [error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[info] [error]     at com.novocode.junit.JUnitRunner$1.execute(JUnitRunner.java:122)
[info] [error]     at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info] [error]     at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info] [error]     at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info] [error]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[info] [error]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info] [error]     at java.lang.Thread.run(Thread.java:745)

```

**Comment by fommil** [comment]
looks like the `ucp`'s `getResource` is returning `null` https://github.com/awh/openjdk7/blob/master/jdk/src/share/classes/sun/misc/URLClassPath.java#L520

**Comment by fommil** [comment]
more likely it is this method https://github.com/awh/openjdk7/blob/master/jdk/src/share/classes/sun/misc/URLClassPath.java#L188

**Comment by fommil** [comment]
interestingly, if we did want to implement our own `URLClassPath` and inject it into the `URLClassLoader`, then these are the only methods used by `URLClassLoader` in OpenJDK7

```
    286:        List<IOException> errors = ucp.closeLoaders();
    327:        ucp.addURL(url);
    337:        return ucp.getURLs();
    358:                        Resource res = ucp.getResource(path, false);
    551:                    return ucp.findResource(name, true);
    555:        return url != null ? ucp.checkURL(url) : null;
    570:        final Enumeration<URL> e = ucp.findResources(name, true);
    590:                    url = ucp.checkURL(u);
```

**Comment by fommil** [comment]
possibly a minor point, but we should perhaps preserve the `URLStreamHandler jarHandler` when cloning the `URLClassPath`

**Comment by fommil** [comment]
also, we should perhaps systematically look up the exact `URLClassLoader` we want to close instead of closing the entire tree. We might be closing classloaders that are used by the compiler.

**Comment by fommil** [comment]
omg, it looks like `URLClassPath` is mutating the `urls` list. We need to build the `url` list up again dynamically.

**Comment by fommil** [comment]
still failing, even with

```scala
        val jarHandlerField = classOf[sun.misc.URLClassPath].getDeclaredField("jarHandler")
        jarHandlerField.setAccessible(true)
        val jarHandler = jarHandlerField.get(urlClassPath)

        // URLs can be added dynamically, so get them from the CP not the CL
        val replacementUrlClassPath = new sun.misc.URLClassPath(urlClassPath.getURLs())
        jarHandlerField.set(replacementUrlClassPath, jarHandler)
```

**Comment by fommil** [comment]
*sigh* https://github.com/awh/openjdk7/blob/master/jdk/src/share/classes/sun/misc/URLClassPath.java#L638 doesn't call `super.close()` which means there is a `JarFile` inside the `Loader` which doesn't always get closed.

**Comment by fommil** [comment]
:joy: https://ci.appveyor.com/project/fommil/sbt-big-project/build/1.0.18
